services:
  nonebot:
    networks:
      - ditingbot
    container_name: nonebot
    depends_on:
      - mysql
      - redis
    build: .
    ports:
      - "6090:6090"

  redis:
    networks:
      - ditingbot
    image: library/redis:latest
    command: redis-server --requirepass 12345678 #Redis 密码
    ports:
      - "6379:6379"

  mysql:
    networks:
      - ditingbot
    image: library/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "13306:3306"

  napcat:
    networks:
      - ditingbot
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: always
    mac_address: 00:e0:70:9a:5d:2b
    privileged: true
    ports:
      - "6099:6099"
      - "30000:3000" #接口测试端口穿透设置
    environment:
      - TZ=Asia/Shanghai
      - NAPCAT_UID=0
      - NAPCAT_GID=0
    volumes:
      - /app/.config/QQ:/app/.config/QQ
      - /app/napcat/config:/app/napcat/config
      - /app/napcat/config:/app/napcat/logs

networks:
  ditingbot:
    driver: bridge