services:
  none-bot:
    container_name: none-bot
    ports:
      - "6090:6090"
    build: .

  redis:
    image: library/redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: library/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "13306:3306"

  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: always
    network_mode: host
    mac_address: 00:e0:70:9a:5d:2b
    privileged: true
    ports:
      - "6099:6099"
    environment:
      - TZ=Asia/Shanghai
      - NAPCAT_UID=0
      - NAPCAT_GID=0
    volumes:
      - /app/.config/QQ:/app/.config/QQ
      - /app/napcat/config:/app/napcat/config
      - /app/napcat/config:/app/napcat/logs