CREATE DATABASE IF NOT EXISTS diting_qq_bot DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS diting_icpc DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
